#pragma once
#include <iostream>
#include <vector>
#include <thread>
#include <chrono>
#include <sstream>
#include <regex>
#include <cassert>
#include <cstring>
#include <algorithm>
#include <cmath>
#include <fstream>
#include <cstdio>
#include <array>
#include <unordered_map>
#include <initializer_list>
#include <tuple>
#include <utility>